name: fake_currency
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.6
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  # pin_code_fields: ^8.0.1
  pinput: ^5.0.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#42a5f5"
  background_image: "assets/images/splash.png"
  android_12:
    image: assets/images/splash.png
